### ISSUE TITLE
Scale parameter in geemap.ee_to_numpy

### ISSUE THREAD

**Issue by nguardo24** [fmemuir/COASTGUARD#10]
![image](https://github.com/fmemuir/COASTGUARD/assets/111257495/61670f61-c64a-4889-b32b-717a0c7e603a)

Hi, I was trying to run the VegetationLine.extract_veglines but it encountered an error related to geemap.ee_to_numpy function in the Image_Processing.py module (line 523) -> TypeError: ee_to_numpy() got an unexpected keyword argument 'scale'.

I read the geemap documentation related to ee_to_numpy() and the parameter is set to None but you can pass it.

If you have any idea about it, I would appreciate it.

Thanks!

**Comment by fmemuir** [comment]
Apologies, the AROSICS coregistering is a recent addition to the features and I forgot to add variables for it to the driver templates. I've amended this now [(see commit here)](https://github.com/fmemuir/COASTGUARD/commit/a0fa5977c3da20312d693b721a586990c6e369d9), but essentially if you want to use coregistering to align satellite images to one another, you should provide a filepath to a reference image somewhere in the driver file. For example, one of the RGB images that are generated by the tool for your site would work:
`settings['reference_coreg_im'] = '/COASTGUARD/Data/EXAMPLESITE/jpg_files/20150817T113146_20150817T113145_T30VWH_RGB.tif')`
If you don't want any coregistering, set that parameter to None:
`settings['reference_coreg_im'] = None`

Hope this helps!

**Comment by nguardo24** [comment]
Hi Freya, thanks a lot about your response. 

I set the `settings['reference_coreg_im'] = None` and the problem related to AROSICS is solved.

Now, there's another issue related with the processing of LANDSAT images, that happened to me in previous versions of the software. The error is the following:

![image](https://github.com/fmemuir/COASTGUARD/assets/111257495/6a00c450-d480-4bb2-bcf2-49e4c8d49b4b)

I did a little debugging of the code and apparently it is passing an empty array to calculate the thresholds related to vegetation. As the array is empty, it can calculate the np.percentile.

Thanks again and we keepo in touch!

**Comment by nguardo24** [comment]
Hi, here are the screenshots:

Classified

![image](https://github.com/fmemuir/COASTGUARD/assets/111257495/cd64f262-c92a-48c3-8a1b-a69e6df155c7)

NDVI

![image](https://github.com/fmemuir/COASTGUARD/assets/111257495/25e63297-bee1-4ca2-ac0c-9b3fb0bb8ed9)

RGB

![image](https://github.com/fmemuir/COASTGUARD/assets/111257495/ec0b3e37-d0d7-453c-b3de-d077072b1410)

**Comment by fmemuir** [comment]
Thanks for the screenshots - while the RGB image looks a little problematic in terms of the colour channels and saturation of the image, clearly vegetation pixels are still being identified by the classifier. 
How large is your buffer zone around your reference shoreline? I ask because the `int_veg_clip` variable that gets read in represents the classified vegetation pixels only within the coastal buffer, and with cloudy pixels masked. If it is very narrow and/or covered by clouds, it may be that there are no  pixels classed as vegetation within the buffer zone to generate a transition zone raster from.

**Comment by nguardo24** [comment]
Hi @fmemuir, thanks for your response.

I understand that `buffer zone around the reference line` references to the variable named `max_dist_ref` but correct me if I'm wrong. In that case, the variable is set to a value of 150 meters. 

Should I increase the value of the variable in order to be able to process Landsat images?

Thank you again and I look forward to hearing from you.

**Comment by nguardo24** [comment]
Hi @fmemuir, I hope you are doing fine.

I have been reviewing the processing using Landsat and I think I found what was happening. Although I sent you the screenshots, in that moment I did not check something that I think results interesting.

As the process was able to create and save the RGB, NDVI and CLASS TIF files before it failed, I loaded them into a QGis project and noticed that they were located in a wrong area. In that sense, the region of interest that I am using is located in the south hemisphere and, for that reason, I assigned the value 32721 to the `projection_epsg` and `image_epsg` variables. This value references to the WGS 84 / UTM zone 21S Coordinate Reference System (EPSG 32721).

Landsat images, in general, are georeferenced in the proyected WGS 84 / UTM system referencing to the North Zone, even for south hemisphere. Taking this into acount, I changed the values of `projection_epsg` and `image_epsg` to 32621 and the process was successful.

**Comment by fmemuir** [comment]
HI @nguardo24, thanks very much for following up - that makes a lot of sense! The coastal buffer will be in whatever coordinate projection system you've provided at the start of the driver file, but if the images themselves are in a different projection system then it won't find any rasters to clip before running the transition zone functions. Although that is a weird result, that even for southern hemisphere locations the UTM zones Landsat provides are always northern. I believe this might have been the reason behind similar errors I was getting for a test run in southern Indonesia! 

I'll make a note of that in the documentation for anyone else facing this, and close this issue thread if you're happy to proceed!
