### ISSUE TITLE
QA 60 Band Issue in Sentinel-2 images 

### ISSUE THREAD

**Issue by IdhamN** [fmemuir/COASTGUARD#13]
Hi Freya,

I encountered a problem when I attempted to extract the vegetation edge in year 2024 using Sentinel-2 images. I received the error message "Image does not contain the band QA60". However, when I change the date to 2023, it works as expected.

![QA 60 band issue](https://github.com/fmemuir/COASTGUARD/assets/142526270/20aa4373-b36c-43a1-bc85-a705a9c7fe8c)

**Comment by fmemuir** [comment]
Thanks for raising this @IdhamN, will investigate with some test ee.Image Sentinel-2 objects for 2024!

**Comment by fmemuir** [comment]
Done some digging, the only relevant issue I can see is here: https://issuetracker.google.com/issues/324827389?pli=1
Basically the newest Sentinel-2 images have changed the QA band names, so they are no longer QA10, QA20 and QA60 but MSK_CLASSI_OPAQUE, MSK_CLASSI_CIRRUS and MSK_CLASSI_SNOW_ICE. The Sentinel-2 documentation doesn't list QA bands either, but 'Scene classification', 'Cloud probability' and 'Snow probability' (https://documentation.dataspace.copernicus.eu/Data/SentinelMissions/Sentinel2.html#sentinel-2-level-1c-top-of-atmosphere-toa). 

I'll add a try/except to use MSK_CLASSI_OPAQUE if QA60 isn't available, as opaque clouds are what we care about masking. However, I'll do some more digging to make sure this is the correct cloud mask band to use from now on, or if this is a temporary band for only some new images.
