### ISSUE TITLE
Coastguard Environment - anaconda errors

### ISSUE THREAD

**Issue by cmac95** [fmemuir/COASTGUARD#4]
ResolvePackageNotFound errors on packages detailed in attached text file. 

[COASTGUARD_environment_errors.txt](https://github.com/fmemuir/COASTGUARD/files/12791848/COASTGUARD_environment_errors.txt)

Also, the environment .yml filename needs to be renamed with the new COASTGUARD branding.

**Comment by fmemuir** [comment]
Have updated host conda, removed build info from .yml and renamed the file. Please git pull and try again, and let me know if there are still ResolvePackageNotFound errors!

**Comment by cmac95** [comment]
Tried to import the new environment, still getting a few errors (see below; less than before?).

Might be worth checking out the simple conda environment in CMT? Just go through each of the .py script files and do the package imports? I might work on it a little more and send you back a potential .yml to try?

ResolvePackageNotFound: 
- nettle=3.8.1
- nss=3.94
- xcb-util-image=0.4.0
- pulseaudio=14.0
- libunistring=0.9.10
- _openmp_mutex=4.5
- libcap=2.64
- brunsli=0.1
- attr=2.5.1
- libidn2=2.3.4
- libgfortran-ng=13.2.0
- xcb-util=0.4.0
- libpciaccess=0.17
- xcb-util-keysyms=0.4.0
- libdrm=2.4.114
- xcb-util-wm=0.4.1
- libuuid=2.38.1
- keyutils=1.6.1
- libev=4.33
- p11-kit=0.24.1
- libtasn1=4.19.0
- readline=8.2
- ld_impl_linux-64=2.40
- alsa-lib=1.2.6.1
- libvpx=1.11.0
- libtool=2.4.7
- libxkbcommon=1.0.3
- libdap4=3.20.6
- gmp=6.2.1
- jack=1.9.18
- libstdcxx-ng=13.2.0
- nspr=4.35
- libcups=2.3.3
- libgcc-ng=13.2.0
- secretstorage=3.3.3
- libva=2.15.0
- libnsl=2.0.0
- ncurses=6.4
- xcb-util-renderutil=0.3.9
- libudev1=249
- gnutls=3.7.8
- tzcode=2023c
- dbus=1.13.6
- libedit=3.1.20191231

**Comment by cmac95** [comment]
Solved using new instructions published in README on main repo page, need to have Python 3.10 installed, then create new "empty" environment (with defaults), then install pyfes, then install the rest of the packages. Worked on both Linux and Windows. Solving environments with libmamba is much faster than default conda solver.
