### ISSUE TITLE
GEE metadata

### ISSUE THREAD

**Issue by cmac95** [fmemuir/COASTGUARD#5]
Code syntax error in Image Download cell of Jupyter Notebook driver. Attempting to resolve myself and if I can I will post solution here.

![image](https://github.com/fmemuir/COASTGUARD/assets/142419267/e3a4dbc3-9c53-4c27-8a91-14b7cb61874b)

**Comment by cmac95** [comment]
It appears to be a bespoke function with two arguments, however "inputs" seems to have multiple components that get split out after being ingested by the function. Not yet sure what data format the "inputs" argument needs to be? 

![image](https://github.com/fmemuir/COASTGUARD/assets/142419267/c40a153a-a892-4627-98c2-0c6a8ad8c8ff)

**Comment by cmac95** [comment]
Issue resolved. 

Passed previous "inputs" variable (dictionary format). 

Change has been saved on local machine git, can provide updated script once running fully (other changes might also be required).

**Comment by fmemuir** [comment]
Typo is from when metadata_collection took more arguments, has since been simplified. Docstring in metadata_collection() has been updated for clarity. Should be all fixed
