### ISSUE TITLE
Remove duplicates - line length

### ISSUE THREAD

**Issue by cmac95** [fmemuir/COASTGUARD#7]
Hi @fmemuir, 

Running into issues with the operation of the new RemoveDuplicates function (approximately Line 600 in Toolbox.py). 

It is a list out of range error which I think stems from the fact that the output['veglines'] list reduces in size as duplicates are deleted. The additional index 'v' appears to refer to values outside of the range of the length of this list, likely ObjectIDs of some sort?

![image](https://github.com/fmemuir/COASTGUARD/assets/142419267/0e6d86a8-e337-4153-8726-c87ec54dfa56)

**Comment by fmemuir** [comment]
Using test Musselburgh _output_ dict with duplicates that was sent over, found several bugs related to the above error:

- Fixed indexing error where size of _output_ changed each loop to be smaller than next index for deletion (now slice using 'idx' variable and not just enumerate ID)
- Added new line to catch rare occurrences of empty geometries (where there's no min length to use for deletion)
- Added documentation to help explain conditions and 'duplicate' sub-functions at the start
